erDiagram
    USER ||--o{ BOX : "has"
    TEAM_POSITIONS o{--|| TEAM: "has"
    TEAM_POSITIONS o{--|| BOX_SPECIES: "positioned at"
    USER||--|| TEAM:"has"
    BOX_SPECIES ||--o{ POKEMON_MOVES : "uses"
    MOVES ||--o{ POKEMON_MOVES : "used by"
    POKEMON_SPECIES ||--o{ BOX_SPECIES : "included in"
    BOX ||--o{ BOX_SPECIES : "contains"
    USER ||--o{ BOX_SPECIES : "has"

    USER {
        int id PK
        string username
        string password
        string email
    }

    POKEMON_SPECIES {
        int id PK
        string name
        string type
        string userImageURL
    }

    BOX {
        int id PK
        int userId FK
        string name
    }

    BOX_SPECIES {
        int id PK
        int pokemonId FK
        int userId FK
        int boxId FK
        int level
        string nature
        string ability
    }

    TEAM {
        int id PK
        string name
        int userId FK
    }

    TEAM_POSITIONS {
        int teamId FK
        int box_speciesId FK
        int position
    }

    MOVES {
        int id PK
        string name 
        int accuracy
        int effect_chance
        int pp   
        int power
    }

    POKEMON_MOVES {
        int box_speciesId PK, FK
        int moveId PK, FK
    }
